## Pandas Basics

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([1,2,3,4,5])
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
obj2 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(obj2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

Create an empty Dataframe

In [5]:
#dataframe
#tạo ra data frame rỗng
emp_df = pd.DataFrame()
print(emp_df)

Empty DataFrame
Columns: []
Index: []

Create a Dataframe from a list

In [8]:
#tao tu list
data = [1,2,3,4]
df_from_list = pd.DataFrame(data=data,index=['a','b','c','d'])
#print(df_from_list)
df_from_list

   0
a  1
b  2
c  3
d  4

In [11]:
# Alternative
data1 =[['A',6],['B',5],['C',3]]
df2 = pd.DataFrame(data = data1,columns = ['col1','col2'])
print(df2.dtypes)
df2

col1      str
col2    int64
dtype: object

  col1  col2
0    A     6
1    B     5
2    C     3

Create a Dateframe from a dict or ndarray

In [14]:
#tu dict hoac ndarray
data2 = {'name':['A','B'],'age':['25','30'],'city':['Berlin','Munich']}
df3 = pd.DataFrame(data = data2,index = ['1','2'])
print(df3)

  name age    city
1    A  25  Berlin
2    B  30  Munich

In [15]:
#list of dict
data4 = [{'A':1,'B':2},{'A':2,'B':3,'C':5}]
df4 = pd.DataFrame(data = data4)
print(df4)

   A  B    C
0  1  2  NaN
1  2  3  5.0

In [16]:
#list of series
data5 = {'col1':pd.Series([1,2,3],index = ['a','b','c']),
         'col2':pd.Series([4,5,6,7],index = ['a','b','c','d'])}
df5 = pd.DataFrame(data = data5,dtype = float)
print(df5)

   col1  col2
a   1.0   4.0
b   2.0   5.0
c   3.0   6.0
d   NaN   7.0

Read file .csv

In [17]:
#doc file csv
df6 = pd.read_csv('pokemon_data.csv')
df6

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [19]:
#doc file txt
df_excel = pd.read_excel('pokemon_data.xlsx')
df_excel

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [22]:
#doc file txt
df7= pd.read_csv('pokemon_data.txt',delimiter ='\t')
df7

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [23]:
# print 3 first lines out
df7.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [24]:
# print the last 4 lines out
df7.tail(4)#4 hang cuoi

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [25]:
# print 7 random lines out
df7.sample(7) # 7hang ngau nhien

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
34,29,Nidoran (Female),Poison,NaN,55,47,52,40,40,41,1,False
326,302,Sableye,Dark,Ghost,50,75,75,65,65,50,3,False
702,641,TornadusIncarnate Forme,Flying,NaN,79,115,70,125,80,111,5,True
743,675,Pangoro,Fighting,Dark,95,124,78,69,71,58,6,False
257,238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False

In [26]:
# print shape of dataframe out
#kich co
df7.shape

(800, 12)

In [46]:
# print all the unique features in column Type 1 out
#xuat tat cac cả thành phần trong type1 ko lăp
df7['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [27]:
# print all column names out
#lấy tất cả tên các cột
df7.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='str')

In [28]:
# print information of the column name
# #lấy thông tin 1 cột
df7['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: str

In [29]:
# print information of column name from line 2 to 6
# #sciling hàng trong 1 cột
df7['Name'][2:6]

2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
5               Charmeleon
Name: Name, dtype: str

In [30]:
# print some columns out
# #đọc 1 vài cột

df7[['Name','HP','Type 2']]

                      Name  HP  Type 2
0                Bulbasaur  45  Poison
1                  Ivysaur  60  Poison
2                 Venusaur  80  Poison
3    VenusaurMega Venusaur  80  Poison
4               Charmander  39     NaN
..                     ...  ..     ...
795                Diancie  50   Fairy
796    DiancieMega Diancie  50   Fairy
797    HoopaHoopa Confined  80   Ghost
798     HoopaHoopa Unbound  80    Dark
799              Volcanion  80   Water

[800 rows x 3 columns]

In [31]:
# print the information of row 2
#đọc hàng
df7.iloc[2]

#                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object

In [33]:
# print more rows from 2 to 6
# #đọc nhiều hàng
df7.iloc[1:6]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False

In [34]:
# print information of index with 1:index of row and 2:index of column
#đọc theo index hang cot, đọc ô ở hàng 1 cột 2
df7.iloc[1,2]

'Grass'

In [35]:
# retrieve data parameters: mean, std, min, ...
#lay thong so data
df7.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [36]:
# sort data by one column
# #sắp xếp data
#1 cột
df7.sort_values(by = 'HP', ascending =False)
#false là từ lớn đến nhỏ, true là ngược lại

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

In [44]:
# sort data by more columns
#sắp xếp nhiều cột
#sap xep 1 cot trước nếu bằng nhau thì mới xếp cột tiếp theo
df7.sort_values(by = ['Type 1','HP'],ascending = [True,False])[:10]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False,162
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False,145
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False,205
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,265
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False,150
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False,132
447,402,Kricketune,Bug,NaN,77,85,51,55,51,65,4,False,162
220,205,Forretress,Bug,Steel,75,90,140,60,60,40,2,False,165
602,542,Leavanny,Bug,Grass,75,103,80,70,80,92,5,False,178
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,5,False,191

In [45]:
# add a column
#them 1 cột
df7['Total']  = df7['HP'] + df7['Attack']

df7.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,94
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,122
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,162
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,180
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,91

In [49]:
# delete a column
# #xóa 1 cột
df7 = df7.drop(columns=['Total'])
df7.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [50]:
# change information in a column
#thay đổi thông tin trong 1 cột
to_replace = {
    'Type 1':'Fairy'
}
value = {
    'Type 1' : 'FAIRY'
}
replace_df = df7.replace(to_replace = to_replace,value = value)

In [51]:
replace_df['Type 1'].unique()

<StringArray>
[   'Grass',     'Fire',    'Water',      'Bug',   'Normal',   'Poison',
 'Electric',   'Ground',    'FAIRY', 'Fighting',  'Psychic',     'Rock',
    'Ghost',      'Ice',   'Dragon',     'Dark',    'Steel',   'Flying']
Length: 18, dtype: str

In [52]:
# turn around
replace_df = df7.replace(to_replace = value,value = to_replace)
replace_df['Type 1'].unique()

<StringArray>
[   'Grass',     'Fire',    'Water',      'Bug',   'Normal',   'Poison',
 'Electric',   'Ground',    'Fairy', 'Fighting',  'Psychic',     'Rock',
    'Ghost',      'Ice',   'Dragon',     'Dark',    'Steel',   'Flying']
Length: 18, dtype: str

In [53]:
# save file as .csv file
#lưu file thành csv
df7.to_csv('a.csv',index = False)

In [54]:
# save file as .xlsx file
#luu excel
df7.to_excel('b.xlsx',index = False)

In [58]:
# save file as .txt file
#luu txt
df7.to_csv('b.txt',index = False ,sep ='\t')

In [57]:
# search data
# #tìm kiếm data
#ten = grass
df7[df7['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [59]:
# search data, print out where Type 1 is Grass and Type 2 is Poison
df7[(df7['Type 1'] == 'Grass')&(df7['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [67]:
# search with a string, print out where in the Name contains the word "Mega"
#tim voi chuoi
df7[df7['Name'].str.contains('Mega')].head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False

In [68]:
# negation, print out where in the Name NOT contains the word "Mega"

df7[~df7['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [69]:
# Statistics
#Count the number of occurrences of species in Type 1
df7.groupby(by ='Type 1').count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112

In [70]:
df7.groupby(by ='Type 1').sum().head()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,23080,CaterpieMetapodButterfreeWeedleKakunaBeedrillB...,FlyingPoisonPoisonPoisonPoisonGrassGrassPoison...,3925,4897,4880,3717,4471,4256,222,0
Dark,14302,UmbreonMurkrowSneaselHoundourHoundoomHoundoomM...,FlyingIceFireFireFireGhostGhostFlyingIceFighti...,2071,2740,2177,2314,2155,2361,125,2
Dragon,15180,DratiniDragonairDragoniteAltariaAltariaMega Al...,FlyingFlyingFairyFlyingFlyingPsychicPsychicPsy...,2666,3588,2764,3099,2843,2657,124,12
Electric,15994,PikachuRaichuMagnemiteMagnetonVoltorbElectrode...,SteelSteelFlyingDragonSteelGhostFireWaterIceFl...,2631,3040,2917,3961,3243,3718,144,4
Fairy,7642,ClefairyClefableCleffaTogepiTogeticSnubbullGra...,FlyingFlying,1260,1046,1117,1335,1440,826,70,1

In [71]:
# use different aggregation
agg = {
    'Attack':'sum',
    'Defense':'count'
}
df7.groupby('Name').agg(agg).head()

                         Attack  Defense
Name
Abomasnow                    92        1
AbomasnowMega Abomasnow     132        1
Abra                         20        1
Absol                       130        1
AbsolMega Absol             150        1

In [72]:
# operations on rows or columns with df.apply
#phep toán trên cot hoac hang df.apply

import numpy as np
df8 = df7[['HP','Attack']]
df8.head()

df8.apply(np.sum, axis = 0)

HP        55407
Attack    63201
dtype: int64